name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testMac:
    runs-on: macOS-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup permissions on gradle file
      run: chmod 777 gradlew
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Android Emulator Runner
      uses: ReactiveCircus/android-emulator-runner@v2.13.0
      with:
        api-level: 29
        script: ./gradlew connectedDebugAndroidTest

#  emulatedTest:
#      runs-on: macos-latest
#      steps:
#      - name: checkout
#        uses: actions/checkout@v2
#      - name: setup permissions on gradle file
#        run: chmod 777 gradlew
#      - name: run tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew connectedCheck
     
#  test:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Android Emulator
#      uses: vgaidarji/android-github-actions-emulator@v1.0.1
      
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
